version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: data_kepegawaian_docker
      POSTGRES_USER: jmadmin
      POSTGRES_PASSWORD: jasamarga123
